-- Generated by scripts/hypr2lua.
-- Source: /home/oldjobobo/Projects/themes/omarchy-awakening-theme/hyprland.conf

local activeBorderColor = {
	colors = { "rgba(ffff00ff)", "rgba(f88416ff)", "rgba(976addff)", "rgba(2976d1ff)", "rgba(ffff00ff)" },
	angle = 95,
}
local inactiveBorderColor = "rgba(ab919144)"
local shadowColor = "rgba(00000088)"

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 10,
		border_size = 3,
		col = {
			active_border = activeBorderColor,
			inactive_border = inactiveBorderColor,
		},
	},
	group = {
		col = {
			border_active = activeBorderColor,
		},
	},
	decoration = {
		rounding = 0,
		active_opacity = 0.99,
		inactive_opacity = 0.95,
		fullscreen_opacity = 1.0,
		blur = {
			enabled = true,
			size = 4,
			passes = 3,
			noise = 0.16,
			contrast = 1.15,
			brightness = 1.0,
			vibrancy = 0.25,
			vibrancy_darkness = 0.22,
		},
		shadow = {
			enabled = true,
			range = 18,
			render_power = 3,
			color = shadowColor,
		},
	},
	animations = {
		enabled = true,
	},
})

hl.curve("livewire", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })
hl.curve("hotdrop", { type = "bezier", points = { { 0.18, 0.9 }, { 0.2, 1 } } })

hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 4,
	bezier = "hotdrop",
})
hl.animation({
	leaf = "windowsIn",
	enabled = true,
	speed = 5,
	bezier = "livewire",
	style = "popin 12%",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 4,
	bezier = "hotdrop",
	style = "popin 78%",
})
hl.animation({
	leaf = "windowsMove",
	enabled = true,
	speed = 4,
	bezier = "livewire",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 5,
	bezier = "livewire",
})
hl.animation({
	leaf = "borderangle",
	enabled = true,
	speed = 22,
	bezier = "linear",
	style = "once",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 4,
	bezier = "hotdrop",
})
hl.animation({
	leaf = "layers",
	enabled = true,
	speed = 4,
	bezier = "hotdrop",
	style = "slidefade",
})
hl.animation({
	leaf = "layersIn",
	enabled = true,
	speed = 4,
	bezier = "livewire",
	style = "slidefade",
})
hl.animation({
	leaf = "layersOut",
	enabled = true,
	speed = 4,
	bezier = "hotdrop",
	style = "fade",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 4,
	bezier = "livewire",
	style = "slidefade",
})

hl.layer_rule({
	no_anim = false,
	match = {
		namespace = "walker",
	},
})
