# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 


[colors]
[colors.primary]
background = "#141010"
foreground = "#ffffff"

[colors.normal]
black   = "#141010"
red     = "#c92b50"
green   = "#ead94d"
yellow  = "#ffbd5b"

blue    = "#1d52a1"
magenta = "#9368d7"
cyan    = "#14aae0"
white   = "#f6deac"


[colors.bright]
black   = "#ab9191"
red     = "#d42b5b"
green   = "#ead94d"

yellow  = "#f6deac"
blue    = "#979dd5"
magenta = "#e3caec"
cyan    = "#c0daf6"
white   = "#ffffff"

[colors.cursor]
text   = "#141010"
cursor = "#ffffff"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
