# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #141010
foreground            #ffffff

# black
color0  #141010
color8  #ab9191

# red
color1  #c92b50
color9  #d42b5b

# green
color2  #ead94d
color10 #f4ea9f

# yellow
color3  #ebbd5b
color11 #f6deac

# blue
color4  #1d52a1
color12 #979dd5

# magenta
color5  #9368d7
color13 #e3caec

#cyan
color6  #14aae0
color14 #c0daf6

#white
color7  #ffffff
color15 #ffffff

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
